//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SaveTextToFile", ReplyAction="http://tempuri.org/IService2/SaveTextToFileResponse")]
        void SaveTextToFile(string nombre, string apellido, string sexo, string email, string direc, string ciudad, string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SaveTextToFile", ReplyAction="http://tempuri.org/IService2/SaveTextToFileResponse")]
        System.Threading.Tasks.Task SaveTextToFileAsync(string nombre, string apellido, string sexo, string email, string direc, string ciudad, string req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Verificar_registro", ReplyAction="http://tempuri.org/IService2/Verificar_registroResponse")]
        bool Verificar_registro(string nombre, string apellidos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Verificar_registro", ReplyAction="http://tempuri.org/IService2/Verificar_registroResponse")]
        System.Threading.Tasks.Task<bool> Verificar_registroAsync(string nombre, string apellidos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : Form.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<Form.ServiceReference2.IService2>, Form.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveTextToFile(string nombre, string apellido, string sexo, string email, string direc, string ciudad, string req) {
            base.Channel.SaveTextToFile(nombre, apellido, sexo, email, direc, ciudad, req);
        }
        
        public System.Threading.Tasks.Task SaveTextToFileAsync(string nombre, string apellido, string sexo, string email, string direc, string ciudad, string req) {
            return base.Channel.SaveTextToFileAsync(nombre, apellido, sexo, email, direc, ciudad, req);
        }
        
        public bool Verificar_registro(string nombre, string apellidos) {
            return base.Channel.Verificar_registro(nombre, apellidos);
        }
        
        public System.Threading.Tasks.Task<bool> Verificar_registroAsync(string nombre, string apellidos) {
            return base.Channel.Verificar_registroAsync(nombre, apellidos);
        }
    }
}
